coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "test"
  - "types/pb"
  - "scripts/"
  - "pkg/rpc/example/"
  - "da/internal/mocks"
  - "da/cmd/*"
