FROM golang:1.24-alpine AS build-env

WORKDIR /src

COPY . .

RUN cd da/cmd/local-da && \
    go mod tidy -compat=1.19 && \
    CGO_ENABLED=0 go build -o /src/local-da .

FROM alpine:3.18.3

WORKDIR /root

COPY --from=build-env /src/local-da /usr/bin/local-da

EXPOSE 7980

ENTRYPOINT ["local-da"]
CMD ["-listen-all"]
