//go:build evm
// +build evm

package e2e

import (
	"context"
	"flag"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/stretchr/testify/require"
	tc "github.com/testcontainers/testcontainers-go/modules/compose"

	"github.com/rollkit/rollkit/execution/evm"
)

var evmSingleBinaryPath string

const (
	DOCKER_PATH = "../../execution/evm/docker"
)

func init() {
	flag.StringVar(&evmSingleBinaryPath, "evm-binary", "evm-single", "evm-single binary")
}

func setupTestRethEngineE2E(t *testing.T) string {
	return evm.SetupTestRethEngine(t, DOCKER_PATH, "jwt.hex")
}

// setupTestRethEngineFullNode sets up a Reth engine test environment for full node using Docker Compose with different ports
func setupTestRethEngineFullNode(t *testing.T) string {
	t.Helper()
	dockerAbsPath, err := filepath.Abs(DOCKER_PATH)
	require.NoError(t, err)
	jwtPath := filepath.Join(dockerAbsPath, "jwttoken")
	err = os.MkdirAll(jwtPath, 0750)
	require.NoError(t, err)

	// Use the full node compose file
	composeFilePath := filepath.Join(dockerAbsPath, "docker-compose-full-node.yml")
	identifier := tc.StackIdentifier(strings.ToLower(t.Name()) + "_fullnode")
	identifier = tc.StackIdentifier(strings.ReplaceAll(string(identifier), "/", "_"))
	identifier = tc.StackIdentifier(strings.ReplaceAll(string(identifier), " ", "_"))
	compose, err := tc.NewDockerComposeWith(tc.WithStackFiles(composeFilePath), identifier)
	require.NoError(t, err, "Failed to create docker compose for full node")
	t.Cleanup(func() {
		ctx := context.Background()
		err := compose.Down(ctx, tc.RemoveOrphans(true), tc.RemoveVolumes(true))
		if err != nil {
			t.Logf("Warning: Failed to tear down docker-compose environment: %v", err)
		}
	})
	ctx := context.Background()
	err = compose.Up(ctx, tc.Wait(true))
	require.NoError(t, err, "Failed to start docker compose for full node")

	// Read the JWT secret that was generated by the Docker container
	jwtFile := filepath.Join(jwtPath, "jwt.hex")
	// Wait for JWT file to be created by the jwt-init-full-node container
	require.Eventually(t, func() bool {
		_, err := os.Stat(jwtFile)
		return err == nil
	}, 10*time.Second, 100*time.Millisecond, "JWT file should be created by Docker container")

	jwtSecretBytes, err := os.ReadFile(jwtFile)
	require.NoError(t, err, "Should be able to read JWT secret from Docker container")
	jwtSecretHex := string(jwtSecretBytes)

	// Wait for full node Reth container (ports 8555, 8561)
	err = waitForRethContainerAt(t, jwtSecretHex, "http://localhost:8555", "http://localhost:8561")
	require.NoError(t, err)
	return jwtSecretHex
}

// waitForRethContainerAt waits for the Reth container to be ready by polling the provided endpoints
func waitForRethContainerAt(t *testing.T, jwtSecret, ethURL, engineURL string) error {
	t.Helper()
	client := &http.Client{Timeout: 100 * time.Millisecond}
	timer := time.NewTimer(30 * time.Second)
	defer timer.Stop()
	for {
		select {
		case <-timer.C:
			return fmt.Errorf("timeout waiting for reth container to be ready")
		default:
			rpcReq := strings.NewReader(`{"jsonrpc":"2.0","method":"net_version","params":[],"id":1}`)
			resp, err := client.Post(ethURL, "application/json", rpcReq)
			if err == nil {
				if err := resp.Body.Close(); err != nil {
					return fmt.Errorf("failed to close response body: %w", err)
				}
				if resp.StatusCode == http.StatusOK {
					// For simplicity, just return success after checking HTTP endpoint
					// The full JWT check is already done in the evm package
					return nil
				}
			}
			time.Sleep(100 * time.Millisecond)
		}
	}
}

// checkTxIncludedAt checks if a transaction with the given hash was included in a block at the specified EVM endpoint
func checkTxIncludedAt(t *testing.T, txHash common.Hash, ethURL string) bool {
	t.Helper()
	rpcClient, err := ethclient.Dial(ethURL)
	if err != nil {
		return false
	}
	defer rpcClient.Close()
	receipt, err := rpcClient.TransactionReceipt(context.Background(), txHash)
	return err == nil && receipt != nil && receipt.Status == 1
}

func TestEvmSequencerE2E(t *testing.T) {
	flag.Parse()
	workDir := t.TempDir()
	nodeHome := filepath.Join(workDir, "evm-agg")
	sut := NewSystemUnderTest(t)

	// 1. Start local DA
	localDABinary := filepath.Join(filepath.Dir(evmSingleBinaryPath), "local-da")
	sut.ExecCmd(localDABinary)
	t.Log("Started local DA")
	time.Sleep(500 * time.Millisecond)

	// 2. Start EVM (Reth) via Docker Compose using setupTestRethEngine logic
	jwtSecret := setupTestRethEngineE2E(t)

	// 3. Get genesis hash from EVM node
	genesisHash := evm.GetGenesisHash(t)
	t.Logf("Genesis hash: %s", genesisHash)

	// 4. Initialize sequencer node
	output, err := sut.RunCmd(evmSingleBinaryPath,
		"init",
		"--rollkit.node.aggregator=true",
		"--rollkit.signer.passphrase", "secret",
		"--home", nodeHome,
	)
	require.NoError(t, err, "failed to init sequencer", output)
	t.Log("Initialized sequencer node")

	// 5. Start sequencer node
	sut.ExecCmd(evmSingleBinaryPath,
		"start",
		"--evm.jwt-secret", jwtSecret,
		"--evm.genesis-hash", genesisHash,
		"--rollkit.node.block_time", "1s",
		"--rollkit.node.aggregator=true",
		"--rollkit.signer.passphrase", "secret",
		"--home", nodeHome,
	)
	sut.AwaitNodeUp(t, "http://127.0.0.1:7331", 10*time.Second)
	t.Log("Sequencer node is up")

	// 6. Submit a transaction to EVM
	lastNonce := uint64(0)
	tx := evm.GetRandomTransaction(t, "cece4f25ac74deb1468965160c7185e07dff413f23fcadb611b05ca37ab0a52e", "0x944fDcD1c868E3cC566C78023CcB38A32cDA836E", "1234", 22000, &lastNonce)
	evm.SubmitTransaction(t, tx)
	t.Log("Submitted test transaction to EVM")

	// 7. Wait for block production and verify transaction inclusion
	require.Eventually(t, func() bool {
		return evm.CheckTxIncluded(t, tx.Hash())
	}, 20*time.Second, 1*time.Second)
	t.Log("Transaction included in EVM block")
}

// extractP2PID extracts the P2P ID from sequencer logs, handling cases where the ID might be split across lines
func extractP2PID(t *testing.T, sut *SystemUnderTest) string {
	t.Helper()

	// Wait for sequencer to generate P2P logs
	time.Sleep(3 * time.Second)

	var p2pID string
	p2pRegex := regexp.MustCompile(`listening on address=/ip4/127\.0\.0\.1/tcp/7676/p2p/([A-Za-z0-9]+)`)
	p2pIDRegex := regexp.MustCompile(`/p2p/([A-Za-z0-9]+)`)
	var allLogLines []string

	// First pass: check output buffer
	sut.outBuff.Do(func(v any) {
		if v != nil {
			line := v.(string)
			allLogLines = append(allLogLines, line)
			if matches := p2pRegex.FindStringSubmatch(line); len(matches) == 2 {
				p2pID = matches[1]
			}
		}
	})

	// Second pass: check error buffer
	if p2pID == "" {
		sut.errBuff.Do(func(v any) {
			if v != nil {
				line := v.(string)
				allLogLines = append(allLogLines, line)
				if matches := p2pRegex.FindStringSubmatch(line); len(matches) == 2 {
					p2pID = matches[1]
				}
			}
		})
	}

	// Third pass: handle split lines by combining logs
	if p2pID == "" {
		combinedLogs := strings.Join(allLogLines, "")
		if matches := p2pRegex.FindStringSubmatch(combinedLogs); len(matches) == 2 {
			p2pID = matches[1]
		} else if matches := p2pIDRegex.FindStringSubmatch(combinedLogs); len(matches) == 2 {
			p2pID = matches[1]
		}
	}

	// Final attempt: wait longer and try again
	if p2pID == "" {
		time.Sleep(3 * time.Second)
		sut.outBuff.Do(func(v any) {
			if v != nil {
				line := v.(string)
				allLogLines = append(allLogLines, line)
				if matches := p2pRegex.FindStringSubmatch(line); len(matches) == 2 {
					p2pID = matches[1]
				}
			}
		})
		sut.errBuff.Do(func(v any) {
			if v != nil {
				line := v.(string)
				allLogLines = append(allLogLines, line)
				if matches := p2pRegex.FindStringSubmatch(line); len(matches) == 2 {
					p2pID = matches[1]
				}
			}
		})

		if p2pID == "" {
			combinedLogs := strings.Join(allLogLines, "")
			if matches := p2pRegex.FindStringSubmatch(combinedLogs); len(matches) == 2 {
				p2pID = matches[1]
			} else if matches := p2pIDRegex.FindStringSubmatch(combinedLogs); len(matches) == 2 {
				p2pID = matches[1]
			}
		}
	}

	require.NotEmpty(t, p2pID, "Could not find P2P ID in sequencer logs")
	return p2pID
}

// setupSequencerNode initializes and starts the sequencer node
func setupSequencerNode(t *testing.T, sut *SystemUnderTest, sequencerHome, jwtSecret, genesisHash string) {
	t.Helper()

	// Initialize sequencer node
	output, err := sut.RunCmd(evmSingleBinaryPath,
		"init",
		"--rollkit.node.aggregator=true",
		"--rollkit.signer.passphrase", "secret",
		"--home", sequencerHome,
	)
	require.NoError(t, err, "failed to init sequencer", output)

	// Start sequencer node
	sut.ExecCmd(evmSingleBinaryPath,
		"start",
		"--evm.jwt-secret", jwtSecret,
		"--evm.genesis-hash", genesisHash,
		"--rollkit.node.block_time", "1s",
		"--rollkit.node.aggregator=true",
		"--rollkit.signer.passphrase", "secret",
		"--home", sequencerHome,
		"--rollkit.da.address", "http://localhost:7980",
		"--rollkit.da.block_time", "15ms",
	)
	sut.AwaitNodeUp(t, "http://127.0.0.1:7331", 10*time.Second)
}

// setupFullNode initializes and starts the full node
func setupFullNode(t *testing.T, sut *SystemUnderTest, fullNodeHome, sequencerHome, fullNodeJwtSecret, genesisHash, p2pID string) {
	t.Helper()

	// Initialize full node
	output, err := sut.RunCmd(evmSingleBinaryPath,
		"init",
		"--home", fullNodeHome,
	)
	require.NoError(t, err, "failed to init full node", output)

	// Copy genesis file from sequencer to full node
	sequencerGenesis := filepath.Join(sequencerHome, "config", "genesis.json")
	fullNodeGenesis := filepath.Join(fullNodeHome, "config", "genesis.json")
	genesisData, err := os.ReadFile(sequencerGenesis)
	require.NoError(t, err, "failed to read sequencer genesis file")
	err = os.WriteFile(fullNodeGenesis, genesisData, 0644)
	require.NoError(t, err, "failed to write full node genesis file")

	// Start full node
	sut.ExecCmd(evmSingleBinaryPath,
		"start",
		"--home", fullNodeHome,
		"--evm.jwt-secret", fullNodeJwtSecret,
		"--evm.genesis-hash", genesisHash,
		"--rollkit.rpc.address", "127.0.0.1:46657",
		"--rollkit.p2p.listen_address", "/ip4/127.0.0.1/tcp/7677",
		"--rollkit.p2p.peers", "/ip4/127.0.0.1/tcp/7676/p2p/"+p2pID,
		"--evm.engine-url", "http://localhost:8561",
		"--evm.eth-url", "http://localhost:8555",
		"--rollkit.da.address", "http://localhost:7980",
		"--rollkit.da.block_time", "15ms",
	)
	sut.AwaitNodeUp(t, "http://127.0.0.1:46657", 10*time.Second)
}

// submitTransactionAndGetBlockNumber submits a transaction to the sequencer and returns the block number it was included in
func submitTransactionAndGetBlockNumber(t *testing.T, sequencerClient *ethclient.Client) (common.Hash, uint64) {
	t.Helper()

	// Submit transaction to sequencer EVM
	lastNonce := uint64(0)
	tx := evm.GetRandomTransaction(t, "cece4f25ac74deb1468965160c7185e07dff413f23fcadb611b05ca37ab0a52e", "0x944fDcD1c868E3cC566C78023CcB38A32cDA836E", "1234", 22000, &lastNonce)
	evm.SubmitTransaction(t, tx)

	// Wait for transaction to be included and get block number
	ctx := context.Background()
	var txBlockNumber uint64
	require.Eventually(t, func() bool {
		receipt, err := sequencerClient.TransactionReceipt(ctx, tx.Hash())
		if err == nil && receipt != nil && receipt.Status == 1 {
			txBlockNumber = receipt.BlockNumber.Uint64()
			return true
		}
		return false
	}, 20*time.Second, 1*time.Second)

	return tx.Hash(), txBlockNumber
}

// verifyTransactionSync verifies that the transaction syncs to the full node in the same block
func verifyTransactionSync(t *testing.T, sequencerClient, fullNodeClient *ethclient.Client, txHash common.Hash, expectedBlockNumber uint64) {
	t.Helper()

	ctx := context.Background()

	// Wait for full node to sync the specific block containing the transaction
	require.Eventually(t, func() bool {
		// Check if full node has reached the block containing the transaction
		fullNodeHeader, err := fullNodeClient.HeaderByNumber(ctx, nil)
		if err != nil {
			return false
		}

		// If full node has reached or passed the transaction block
		if fullNodeHeader.Number.Uint64() >= expectedBlockNumber {
			// Verify the transaction exists in the full node
			receipt, err := fullNodeClient.TransactionReceipt(ctx, txHash)
			if err == nil && receipt != nil && receipt.Status == 1 {
				return receipt.BlockNumber.Uint64() == expectedBlockNumber
			}
		}
		return false
	}, 60*time.Second, 2*time.Second, "Full node should sync the block containing the transaction")

	// Final verification - both nodes should have the transaction in the same block
	sequencerReceipt, err := sequencerClient.TransactionReceipt(ctx, txHash)
	require.NoError(t, err, "Should get transaction receipt from sequencer")

	fullNodeReceipt, err := fullNodeClient.TransactionReceipt(ctx, txHash)
	require.NoError(t, err, "Should get transaction receipt from full node")

	require.Equal(t, sequencerReceipt.BlockNumber.Uint64(), fullNodeReceipt.BlockNumber.Uint64(),
		"Transaction should be in the same block number on both sequencer and full node")
}

func TestEvmSequencerWithFullNodeE2E(t *testing.T) {
	flag.Parse()
	workDir := t.TempDir()
	sequencerHome := filepath.Join(workDir, "evm-sequencer")
	fullNodeHome := filepath.Join(workDir, "evm-full-node")
	sut := NewSystemUnderTest(t)

	// === SETUP PHASE ===

	// Start local DA layer
	localDABinary := "local-da"
	if evmSingleBinaryPath != "evm-single" {
		localDABinary = filepath.Join(filepath.Dir(evmSingleBinaryPath), "local-da")
	}
	sut.ExecCmd(localDABinary)
	t.Log("Started local DA")
	time.Sleep(500 * time.Millisecond)

	// Start EVM instances (sequencer and full node)
	jwtSecret := setupTestRethEngineE2E(t)
	fullNodeJwtSecret := setupTestRethEngineFullNode(t)
	genesisHash := evm.GetGenesisHash(t)
	t.Logf("Genesis hash: %s", genesisHash)

	// === SEQUENCER SETUP ===

	setupSequencerNode(t, sut, sequencerHome, jwtSecret, genesisHash)
	t.Log("Sequencer node is up")

	// === FULL NODE SETUP ===

	p2pID := extractP2PID(t, sut)
	t.Logf("Extracted P2P ID: %s", p2pID)

	setupFullNode(t, sut, fullNodeHome, sequencerHome, fullNodeJwtSecret, genesisHash, p2pID)
	t.Log("Full node is up")

	// Allow time for nodes to establish sync
	time.Sleep(5 * time.Second)

	// === TESTING PHASE ===

	// Connect to both EVM instances
	sequencerClient, err := ethclient.Dial("http://localhost:8545")
	require.NoError(t, err, "Should be able to connect to sequencer EVM")
	defer sequencerClient.Close()

	fullNodeClient, err := ethclient.Dial("http://localhost:8555")
	require.NoError(t, err, "Should be able to connect to full node EVM")
	defer fullNodeClient.Close()

	// Submit transaction and verify sync
	txHash, txBlockNumber := submitTransactionAndGetBlockNumber(t, sequencerClient)
	t.Logf("Transaction included in sequencer block %d", txBlockNumber)

	t.Log("Waiting for full node to sync the transaction block...")
	verifyTransactionSync(t, sequencerClient, fullNodeClient, txHash, txBlockNumber)

	t.Logf("✅ Test PASSED: Transaction synced successfully in block %d on both nodes", txBlockNumber)
}
