// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: rollkit/v1/execution.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenesisTime   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	InitialHeight uint64                 `protobuf:"varint,2,opt,name=initial_height,json=initialHeight,proto3" json:"initial_height,omitempty"`
	ChainId       string                 `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitChainRequest) Reset() {
	*x = InitChainRequest{}
	mi := &file_rollkit_v1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitChainRequest) ProtoMessage() {}

func (x *InitChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitChainRequest.ProtoReflect.Descriptor instead.
func (*InitChainRequest) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_execution_proto_rawDescGZIP(), []int{0}
}

func (x *InitChainRequest) GetGenesisTime() *timestamppb.Timestamp {
	if x != nil {
		return x.GenesisTime
	}
	return nil
}

func (x *InitChainRequest) GetInitialHeight() uint64 {
	if x != nil {
		return x.InitialHeight
	}
	return 0
}

func (x *InitChainRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type InitChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateRoot     []byte                 `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	MaxBytes      uint64                 `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitChainResponse) Reset() {
	*x = InitChainResponse{}
	mi := &file_rollkit_v1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitChainResponse) ProtoMessage() {}

func (x *InitChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitChainResponse.ProtoReflect.Descriptor instead.
func (*InitChainResponse) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *InitChainResponse) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *InitChainResponse) GetMaxBytes() uint64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type GetTxsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           [][]byte               `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTxsResponse) Reset() {
	*x = GetTxsResponse{}
	mi := &file_rollkit_v1_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTxsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxsResponse) ProtoMessage() {}

func (x *GetTxsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxsResponse.ProtoReflect.Descriptor instead.
func (*GetTxsResponse) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_execution_proto_rawDescGZIP(), []int{2}
}

func (x *GetTxsResponse) GetTxs() [][]byte {
	if x != nil {
		return x.Txs
	}
	return nil
}

type ExecuteTxsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           [][]byte               `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	BlockHeight   uint64                 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PrevStateRoot []byte                 `protobuf:"bytes,4,opt,name=prev_state_root,json=prevStateRoot,proto3" json:"prev_state_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTxsRequest) Reset() {
	*x = ExecuteTxsRequest{}
	mi := &file_rollkit_v1_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTxsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTxsRequest) ProtoMessage() {}

func (x *ExecuteTxsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTxsRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTxsRequest) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_execution_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteTxsRequest) GetTxs() [][]byte {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *ExecuteTxsRequest) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *ExecuteTxsRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExecuteTxsRequest) GetPrevStateRoot() []byte {
	if x != nil {
		return x.PrevStateRoot
	}
	return nil
}

type ExecuteTxsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UpdatedStateRoot []byte                 `protobuf:"bytes,1,opt,name=updated_state_root,json=updatedStateRoot,proto3" json:"updated_state_root,omitempty"`
	MaxBytes         uint64                 `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecuteTxsResponse) Reset() {
	*x = ExecuteTxsResponse{}
	mi := &file_rollkit_v1_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTxsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTxsResponse) ProtoMessage() {}

func (x *ExecuteTxsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTxsResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTxsResponse) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_execution_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteTxsResponse) GetUpdatedStateRoot() []byte {
	if x != nil {
		return x.UpdatedStateRoot
	}
	return nil
}

func (x *ExecuteTxsResponse) GetMaxBytes() uint64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type SetFinalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight   uint64                 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFinalRequest) Reset() {
	*x = SetFinalRequest{}
	mi := &file_rollkit_v1_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFinalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFinalRequest) ProtoMessage() {}

func (x *SetFinalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollkit_v1_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFinalRequest.ProtoReflect.Descriptor instead.
func (*SetFinalRequest) Descriptor() ([]byte, []int) {
	return file_rollkit_v1_execution_proto_rawDescGZIP(), []int{5}
}

func (x *SetFinalRequest) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

var File_rollkit_v1_execution_proto protoreflect.FileDescriptor

const file_rollkit_v1_execution_proto_rawDesc = "" +
	"\n" +
	"\x1arollkit/v1/execution.proto\x12\n" +
	"rollkit.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n" +
	"\x10InitChainRequest\x12=\n" +
	"\fgenesis_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vgenesisTime\x12%\n" +
	"\x0einitial_height\x18\x02 \x01(\x04R\rinitialHeight\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\tR\achainId\"O\n" +
	"\x11InitChainResponse\x12\x1d\n" +
	"\n" +
	"state_root\x18\x01 \x01(\fR\tstateRoot\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\x04R\bmaxBytes\"\"\n" +
	"\x0eGetTxsResponse\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\fR\x03txs\"\xaa\x01\n" +
	"\x11ExecuteTxsRequest\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\fR\x03txs\x12!\n" +
	"\fblock_height\x18\x02 \x01(\x04R\vblockHeight\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12&\n" +
	"\x0fprev_state_root\x18\x04 \x01(\fR\rprevStateRoot\"_\n" +
	"\x12ExecuteTxsResponse\x12,\n" +
	"\x12updated_state_root\x18\x01 \x01(\fR\x10updatedStateRoot\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\x04R\bmaxBytes\"4\n" +
	"\x0fSetFinalRequest\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight2\xb0\x02\n" +
	"\x10ExecutionService\x12J\n" +
	"\tInitChain\x12\x1c.rollkit.v1.InitChainRequest\x1a\x1d.rollkit.v1.InitChainResponse\"\x00\x12>\n" +
	"\x06GetTxs\x12\x16.google.protobuf.Empty\x1a\x1a.rollkit.v1.GetTxsResponse\"\x00\x12M\n" +
	"\n" +
	"ExecuteTxs\x12\x1d.rollkit.v1.ExecuteTxsRequest\x1a\x1e.rollkit.v1.ExecuteTxsResponse\"\x00\x12A\n" +
	"\bSetFinal\x12\x1b.rollkit.v1.SetFinalRequest\x1a\x16.google.protobuf.Empty\"\x00B0Z.github.com/rollkit/rollkit/types/pb/rollkit/v1b\x06proto3"

var (
	file_rollkit_v1_execution_proto_rawDescOnce sync.Once
	file_rollkit_v1_execution_proto_rawDescData []byte
)

func file_rollkit_v1_execution_proto_rawDescGZIP() []byte {
	file_rollkit_v1_execution_proto_rawDescOnce.Do(func() {
		file_rollkit_v1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rollkit_v1_execution_proto_rawDesc), len(file_rollkit_v1_execution_proto_rawDesc)))
	})
	return file_rollkit_v1_execution_proto_rawDescData
}

var file_rollkit_v1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rollkit_v1_execution_proto_goTypes = []any{
	(*InitChainRequest)(nil),      // 0: rollkit.v1.InitChainRequest
	(*InitChainResponse)(nil),     // 1: rollkit.v1.InitChainResponse
	(*GetTxsResponse)(nil),        // 2: rollkit.v1.GetTxsResponse
	(*ExecuteTxsRequest)(nil),     // 3: rollkit.v1.ExecuteTxsRequest
	(*ExecuteTxsResponse)(nil),    // 4: rollkit.v1.ExecuteTxsResponse
	(*SetFinalRequest)(nil),       // 5: rollkit.v1.SetFinalRequest
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_rollkit_v1_execution_proto_depIdxs = []int32{
	6, // 0: rollkit.v1.InitChainRequest.genesis_time:type_name -> google.protobuf.Timestamp
	6, // 1: rollkit.v1.ExecuteTxsRequest.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: rollkit.v1.ExecutionService.InitChain:input_type -> rollkit.v1.InitChainRequest
	7, // 3: rollkit.v1.ExecutionService.GetTxs:input_type -> google.protobuf.Empty
	3, // 4: rollkit.v1.ExecutionService.ExecuteTxs:input_type -> rollkit.v1.ExecuteTxsRequest
	5, // 5: rollkit.v1.ExecutionService.SetFinal:input_type -> rollkit.v1.SetFinalRequest
	1, // 6: rollkit.v1.ExecutionService.InitChain:output_type -> rollkit.v1.InitChainResponse
	2, // 7: rollkit.v1.ExecutionService.GetTxs:output_type -> rollkit.v1.GetTxsResponse
	4, // 8: rollkit.v1.ExecutionService.ExecuteTxs:output_type -> rollkit.v1.ExecuteTxsResponse
	7, // 9: rollkit.v1.ExecutionService.SetFinal:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rollkit_v1_execution_proto_init() }
func file_rollkit_v1_execution_proto_init() {
	if File_rollkit_v1_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rollkit_v1_execution_proto_rawDesc), len(file_rollkit_v1_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rollkit_v1_execution_proto_goTypes,
		DependencyIndexes: file_rollkit_v1_execution_proto_depIdxs,
		MessageInfos:      file_rollkit_v1_execution_proto_msgTypes,
	}.Build()
	File_rollkit_v1_execution_proto = out.File
	file_rollkit_v1_execution_proto_goTypes = nil
	file_rollkit_v1_execution_proto_depIdxs = nil
}
